"""Plans API routes"""
from uuid import UUID
from typing import List
from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session

from dsagent.api.deps import get_db
from dsagent.db.schemas import PlanCreate, PlanResponse
from dsagent.db.repositories import PlanRepository, ItemRepository
from dsagent.agents.planner import PlannerAgent

router = APIRouter(prefix="/api/v1/plans", tags=["plans"])


@router.post("", response_model=PlanResponse, status_code=status.HTTP_201_CREATED)
def create_plan(
    plan: PlanCreate,
    db: Session = Depends(get_db)
):
    """Create a new plan (generated by Planner Agent)"""
    # This would typically be called by the Planner Agent
    # For now, just return a placeholder
    return {"status": "not_implemented", "message": "Use Planner Agent to generate plans"}


@router.get("/{plan_id}")
def get_plan(
    plan_id: UUID,
    db: Session = Depends(get_db)
):
    """Get plan with all items"""
    repo = PlanRepository(db)
    plan = repo.get(plan_id)
    
    if not plan:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Plan not found"
        )
    
    item_repo = ItemRepository(db)
    items = item_repo.get_by_plan(plan_id)
    
    return {
        "id": str(plan.id),
        "project_id": str(plan.project_id),
        "status": plan.status,
        "items": [
            {
                "id": str(item.id),
                "skill_name": item.skill_name,
                "phase": item.phase,
                "title": item.title,
                "description": item.description,
                "status": item.status
            }
            for item in items
        ]
    }


@router.post("/{plan_id}/approve")
def approve_plan(
    plan_id: UUID,
    db: Session = Depends(get_db)
):
    """Approve a plan"""
    repo = PlanRepository(db)
    plan = repo.get(plan_id)
    
    if not plan:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Plan not found"
        )
    
    plan.status = "approved"
    repo.update(plan)
    
    return {"status": "approved", "plan_id": str(plan_id)}


@router.post("/{plan_id}/reject")
def reject_plan(
    plan_id: UUID,
    reason: str = "",
    db: Session = Depends(get_db)
):
    """Reject a plan"""
    repo = PlanRepository(db)
    plan = repo.get(plan_id)
    
    if not plan:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="Plan not found"
        )
    
    plan.status = "rejected"
    repo.update(plan)
    
    return {"status": "rejected", "plan_id": str(plan_id), "reason": reason}
